// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlatformApi.Data;

#nullable disable

namespace PlatformApi.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20250831195941_InitialMysql")]
    partial class InitialMysql
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_claims_user_id");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_logins_user_id");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("longtext")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_user_tokens");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("PlatformApi.Models.AuthUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PlatformApi.Models.Permission", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_mod_by");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_mod_date");

                    b.Property<string>("ModifiedSource")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("modify_source");

                    b.Property<int?>("RoleScope")
                        .HasColumnType("int")
                        .HasColumnName("role_scope");

                    b.HasKey("Code")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "default:all",
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Default Basic Access Permission",
                            RoleScope = 8
                        },
                        new
                        {
                            Code = "systemadmin.manage.permissions",
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SysAdmin Manage Permissions",
                            RoleScope = 1
                        },
                        new
                        {
                            Code = "systemadmin.manage.users",
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SysAdmin Manage Users",
                            RoleScope = 1
                        },
                        new
                        {
                            Code = "systemadmin.manage.tenants",
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SysAdmin Manage Tenants",
                            RoleScope = 1
                        },
                        new
                        {
                            Code = "systemadmin.manage.sites",
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "SysAdmin Manage Sites",
                            RoleScope = 1
                        },
                        new
                        {
                            Code = "admins.lookup.users",
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Admins Lookup Users",
                            RoleScope = 1
                        },
                        new
                        {
                            Code = "tenant.admin.manage.users",
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tenant Manage Users",
                            RoleScope = 2
                        },
                        new
                        {
                            Code = "tenant.manage.config",
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tenant Manage Config",
                            RoleScope = 2
                        },
                        new
                        {
                            Code = "tenant.access.all.sites",
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tenant Access All Sites",
                            RoleScope = 2
                        },
                        new
                        {
                            Code = "site.manage.config",
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Site Manage Config",
                            RoleScope = 4
                        },
                        new
                        {
                            Code = "site.manage.users",
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Site Manage Users",
                            RoleScope = 4
                        });
                });

            modelBuilder.Entity("PlatformApi.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_revoked");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_mod_by");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_mod_date");

                    b.Property<string>("ModifiedSource")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("modify_source");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("char(36)")
                        .HasColumnName("site_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("token");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_refresh_tokens");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_user_refresh_tokens_site_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_refresh_tokens_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_refresh_tokens_user_id");

                    b.ToTable("user_refresh_tokens", (string)null);
                });

            modelBuilder.Entity("PlatformApi.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystemRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system_role");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_mod_by");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_mod_date");

                    b.Property<string>("ModifiedSource")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("modify_source");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)")
                        .HasColumnName("name");

                    b.Property<int>("Scope")
                        .HasColumnType("int")
                        .HasColumnName("scope");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("char(36)")
                        .HasColumnName("site_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Scope")
                        .HasDatabaseName("ix_roles_scope");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_roles_site_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_roles_tenant_id");

                    b.HasIndex("TenantId", "Scope")
                        .HasDatabaseName("ix_roles_tenant_id_scope");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("08dd1343-9ab2-4439-8295-da20d3e49321"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemRole = false,
                            Name = "SuperAdmin",
                            Scope = 1
                        },
                        new
                        {
                            Id = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemRole = false,
                            Name = "DefaultUser",
                            Scope = 8
                        },
                        new
                        {
                            Id = new Guid("87ad21c9-d406-4f00-90dd-d8d9ee99805b"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemRole = false,
                            Name = "TenantAdmin",
                            Scope = 2
                        },
                        new
                        {
                            Id = new Guid("cc84f8ff-2699-4c69-b9a4-172076528322"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsSystemRole = false,
                            Name = "SiteAdmin",
                            Scope = 4
                        });
                });

            modelBuilder.Entity("PlatformApi.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_mod_by");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_mod_date");

                    b.Property<string>("ModifiedSource")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("modify_source");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("permission_code");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionCode")
                        .HasDatabaseName("ix_role_permissions_permission_code");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_role_permissions_role_id");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-7890-abcd-ef1234567890"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "default:all",
                            RoleId = new Guid("f47ac10b-58cc-4372-a567-0e02b2c3d479")
                        },
                        new
                        {
                            Id = new Guid("c08a610d-f07d-436e-839e-31f5b6ffc87d"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "systemadmin.manage.permissions",
                            RoleId = new Guid("08dd1343-9ab2-4439-8295-da20d3e49321")
                        },
                        new
                        {
                            Id = new Guid("7ee43803-5d35-425f-8392-f4de1df37e05"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "systemadmin.manage.users",
                            RoleId = new Guid("08dd1343-9ab2-4439-8295-da20d3e49321")
                        },
                        new
                        {
                            Id = new Guid("311a22a5-1100-4917-83e6-6bf7994493dd"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "systemadmin.manage.tenants",
                            RoleId = new Guid("08dd1343-9ab2-4439-8295-da20d3e49321")
                        },
                        new
                        {
                            Id = new Guid("a4b5c6d7-e8f9-0123-4567-89abcdef0123"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "tenant.admin.manage.users",
                            RoleId = new Guid("08dd1343-9ab2-4439-8295-da20d3e49321")
                        },
                        new
                        {
                            Id = new Guid("b5c6d7e8-f9a0-1234-5678-9abcdef01234"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "tenant.manage.config",
                            RoleId = new Guid("08dd1343-9ab2-4439-8295-da20d3e49321")
                        },
                        new
                        {
                            Id = new Guid("c6d7e8f9-a0b1-2345-6789-abcdef012345"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "site.manage.config",
                            RoleId = new Guid("08dd1343-9ab2-4439-8295-da20d3e49321")
                        },
                        new
                        {
                            Id = new Guid("d7e8f9a0-b1c2-3456-789a-bcdef0123456"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "site.manage.users",
                            RoleId = new Guid("08dd1343-9ab2-4439-8295-da20d3e49321")
                        },
                        new
                        {
                            Id = new Guid("e8f9a0b1-c2d3-4567-89ab-cdef01234567"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "systemadmin.manage.sites",
                            RoleId = new Guid("08dd1343-9ab2-4439-8295-da20d3e49321")
                        },
                        new
                        {
                            Id = new Guid("f9a0b1c2-d3e4-5678-9abc-def012345678"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "admins.lookup.users",
                            RoleId = new Guid("08dd1343-9ab2-4439-8295-da20d3e49321")
                        },
                        new
                        {
                            Id = new Guid("a0b1c2d3-e4f5-6789-abcd-ef0123456789"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "tenant.access.all.sites",
                            RoleId = new Guid("08dd1343-9ab2-4439-8295-da20d3e49321")
                        },
                        new
                        {
                            Id = new Guid("70a47010-46a0-4a87-9f0e-b0326316e580"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "tenant.admin.manage.users",
                            RoleId = new Guid("87ad21c9-d406-4f00-90dd-d8d9ee99805b")
                        },
                        new
                        {
                            Id = new Guid("1237a8e7-96cc-47d4-a2f3-9d66fe3e3f6d"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "tenant.manage.config",
                            RoleId = new Guid("87ad21c9-d406-4f00-90dd-d8d9ee99805b")
                        },
                        new
                        {
                            Id = new Guid("936456cc-8ce2-4bd5-9ba4-1b79d271fe01"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "site.manage.config",
                            RoleId = new Guid("cc84f8ff-2699-4c69-b9a4-172076528322")
                        },
                        new
                        {
                            Id = new Guid("d22bec2f-9a68-4ecf-aa81-c550f57acaa9"),
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            PermissionCode = "site.manage.users",
                            RoleId = new Guid("cc84f8ff-2699-4c69-b9a4-172076528322")
                        });
                });

            modelBuilder.Entity("PlatformApi.Models.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_mod_by");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_mod_date");

                    b.Property<string>("ModifiedSource")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("modify_source");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sites");

                    b.HasIndex(new[] { "Code", "TenantId" }, "IX_site_code_tenant_unique")
                        .IsUnique()
                        .HasDatabaseName("ix_sites_code_tenant_id");

                    b.HasIndex(new[] { "Name", "TenantId" }, "IX_site_name_tenant_unique")
                        .IsUnique()
                        .HasDatabaseName("ix_sites_name_tenant_id");

                    b.HasIndex(new[] { "TenantId" }, "IX_site_tenant_id")
                        .HasDatabaseName("ix_sites_tenant_id");

                    b.ToTable("sites", (string)null);
                });

            modelBuilder.Entity("PlatformApi.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_mod_by");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_mod_date");

                    b.Property<string>("ModifiedSource")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("modify_source");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("SubDomain")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("sub_domain");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_name");

                    b.HasIndex("SubDomain")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_sub_domain");

                    b.ToTable("tenants", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("baab4de5-fe68-4940-996e-5914f8234863"),
                            Code = "Default",
                            CreateDate = new DateTime(2024, 11, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Test Tenant",
                            SubDomain = "default"
                        });
                });

            modelBuilder.Entity("PlatformApi.Models.TenantConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<string>("LogoPath")
                        .HasColumnType("longtext")
                        .HasColumnName("logo_path");

                    b.Property<string>("PrimaryColor")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("primary_color");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_tenant_configs");

                    b.HasIndex("TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_configs_tenant_id");

                    b.ToTable("tenant_configs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1e2d3c4-b5a6-9870-cdef-123456789abc"),
                            PrimaryColor = "#007bff",
                            TenantId = new Guid("baab4de5-fe68-4940-996e-5914f8234863")
                        });
                });

            modelBuilder.Entity("PlatformApi.Models.UserInvitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("InvitationToken")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("invitation_token");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_used");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_mod_by");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_mod_date");

                    b.Property<string>("ModifiedSource")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("modify_source");

                    b.Property<int>("Scope")
                        .HasColumnType("int")
                        .HasColumnName("scope");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("char(36)")
                        .HasColumnName("site_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_user_invitations");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_user_invitations_email");

                    b.HasIndex("InvitationToken")
                        .IsUnique()
                        .HasDatabaseName("ix_user_invitations_invitation_token");

                    b.ToTable("user_invitations", (string)null);
                });

            modelBuilder.Entity("PlatformApi.Models.UserRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("create_date");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("create_by");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_mod_by");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_mod_date");

                    b.Property<string>("ModifiedSource")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("modify_source");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)")
                        .HasColumnName("role_id");

                    b.Property<int>("Scope")
                        .HasColumnType("int")
                        .HasColumnName("scope");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("char(36)")
                        .HasColumnName("site_id");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("char(36)")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_user_roles_site_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_user_roles_tenant_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_roles_user_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("PlatformApi.Models.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_claims_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("PlatformApi.Models.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_logins_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("PlatformApi.Models.AuthUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_tokens_users_user_id");
                });

            modelBuilder.Entity("PlatformApi.Models.RefreshToken", b =>
                {
                    b.HasOne("PlatformApi.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .HasConstraintName("fk_user_refresh_tokens_sites_site_id");

                    b.HasOne("PlatformApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_user_refresh_tokens_tenants_tenant_id");

                    b.HasOne("PlatformApi.Models.AuthUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_refresh_tokens_users_user_id");

                    b.Navigation("Site");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlatformApi.Models.RolePermission", b =>
                {
                    b.HasOne("PlatformApi.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_code");

                    b.HasOne("PlatformApi.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("PlatformApi.Models.Site", b =>
                {
                    b.HasOne("PlatformApi.Models.Tenant", "Tenant")
                        .WithMany("Sites")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sites_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PlatformApi.Models.TenantConfig", b =>
                {
                    b.HasOne("PlatformApi.Models.Tenant", "Tenant")
                        .WithOne("TenantConfig")
                        .HasForeignKey("PlatformApi.Models.TenantConfig", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_configs_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PlatformApi.Models.UserRoles", b =>
                {
                    b.HasOne("PlatformApi.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("PlatformApi.Models.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .HasConstraintName("fk_user_roles_sites_site_id");

                    b.HasOne("PlatformApi.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .HasConstraintName("fk_user_roles_tenants_tenant_id");

                    b.HasOne("PlatformApi.Models.AuthUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("Site");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PlatformApi.Models.AuthUser", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PlatformApi.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("PlatformApi.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("PlatformApi.Models.Tenant", b =>
                {
                    b.Navigation("Sites");

                    b.Navigation("TenantConfig");
                });
#pragma warning restore 612, 618
        }
    }
}
